name: CI
on:
  push:
    branches:
      - '**'
jobs:
  build:
    name: '${{ matrix.os }}: Build, lint, test'

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      PGHOST: localhost
      PGDATABASE: preflight_test_project_next_js_passing
      PGUSERNAME: preflight_test_project_next_js_passing
      PGPASSWORD: preflight_test_project_next_js_passing
    steps:
      - uses: ikalnytskyi/action-setup-postgres@v5
        with:
          username: ${{ env.PGUSERNAME }}
          password: ${{ env.PGPASSWORD }}
          database: ${{ env.PGDATABASE }}
      # To avoid CRLF in Windows tests, which cause problems with Prettier:
      # https://github.com/upleveled/preflight/runs/1824397400
      #
      # Suggested here: https://github.com/actions/checkout/issues/250#issuecomment-635267458
      # Example repo: https://github.com/ghdl/ghdl/blob/aa63b5efcd2be66acc26443032df2b251e4b1a7a/.github/workflows/Test.yml#L230-L232
      - name: Use LF instead of CRLF for clone
        run: git config --global core.autocrlf input

      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 'latest'

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm install
        if: runner.os != 'Windows'
        working-directory: docker

      - name: Lint
        if: runner.os != 'Windows'
        run: pnpm lint

      - run: pnpm tsc --build
        if: runner.os != 'Windows'

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test -- --ci --maxWorkers=2
