name: Build and push Docker image
on:
  create:
  workflow_dispatch:
    inputs:
      dispatchConfirmation:
        description: 'Please confirm the workflow dispatch'
        required: true
        default: 'Workflow dispatch confirmed'

jobs:
  build:
    if: ${{ github.event.ref_type == 'tag' || github.event.inputs.dispatchConfirmation == 'Workflow dispatch confirmed' }}
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Compile TypeScript and build Docker images
        run: yarn build-docker-ts

      # Publish to container registry
      - name: Log in to the Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
      - name: Build and push Docker image
        uses: docker/build-push-action@6e95f19fb8c9e00a1a391941edbc0ae30c1799f7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
