name: Build and push Docker image
on:
  create:
  workflow_dispatch:
    inputs:
      dispatchConfirmation:
        description: 'Please confirm the workflow dispatch'
        required: true
        default: 'Workflow dispatch confirmed'

jobs:
  build:
    if: ${{ github.event.ref_type == 'tag' || github.event.inputs.dispatchConfirmation == 'Workflow dispatch confirmed' }}
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Compile TypeScript and build Docker images
        run: yarn build-docker-ts

      # Publish to container registry
      - name: Log in to the Container registry
        uses: docker/login-action@7f47463f5646678eb7ccf8f0f2e2d0896916a10a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@548e2346a9987b56d8a4104fe776321ff8e23440
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
      - name: Build and push Docker image
        uses: docker/build-push-action@0a196c9debcb2a8c801667d284cc098c0fe08d7f
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
