name: Build and push Docker image
on:
  create:
  workflow_dispatch:
    inputs:
      dispatchConfirmation:
        description: 'Please confirm the workflow dispatch'
        required: true
        default: 'Workflow dispatch confirmed'

jobs:
  build:
    if: ${{ github.event.ref_type == 'tag' || github.event.inputs.dispatchConfirmation == 'Workflow dispatch confirmed' }}
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Compile TypeScript and build Docker images
        run: yarn build-docker-ts

      # Publish to container registry
      - name: Log in to the Container registry
        uses: docker/login-action@d398f07826957cd0a18ea1b059cf1207835e60bc
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@ee266832e57cb510bc6060ce5129df0529f119df
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
      - name: Build and push Docker image
        uses: docker/build-push-action@965c6a410d446a30e95d35052c67d6eded60dad6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
