name: CI
on:
  push:
    branches:
      - '**'
jobs:
  build:
    name: '${{ matrix.os }}: Build, lint, test'

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # To avoid CRLF in Windows tests, which cause problems with Prettier:
      # https://github.com/upleveled/preflight/runs/1824397400
      #
      # Suggested here: https://github.com/actions/checkout/issues/250#issuecomment-635267458
      # Example repo: https://github.com/ghdl/ghdl/blob/aa63b5efcd2be66acc26443032df2b251e4b1a7a/.github/workflows/Test.yml#L230-L232
      - name: Use LF instead of CRLF for clone
        run: git config --global core.autocrlf input

      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 'latest'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - run: pnpm install

      - name: Lint
        run: pnpm lint

      - run: pnpm tsc
      - run: pnpm tsc --project bin/tsconfig.json
      - run: pnpm tsc --project docker/tsconfig.json
      - run: pnpm tsc --project tsconfig.nonsrc.json

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test -- --ci --maxWorkers=2
